name: "Compile the homework"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: "Make index page"
        run: cp README.md dist/index.md
      - name: "GitHub Pages deployment"
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "dist/"
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
